name: con người tiến hpaa

on:
  workflow_dispatch:


jobs:
  cloudphone:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Cài phần mềm
        run: |
          sudo apt update -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
      - name: Tạo Cloudflare Tunnel & gửi Webhook
        run: |
          docker run -d --name cloudflared cloudflare/cloudflared:latest tunnel --url http://localhost:6080    
      

      - name: Khởi chạy máy ảo QEMU (6 giờ)
        run: |
          sudo chmod 666 /dev/kvm
          echo "✅ Khởi động máy ảo Android..."
          docker run -d -p 6080:6080 -e EMULATOR_DEVICE="Samsung Galaxy S10" -e WEB_VNC=true --device /dev/kvm --name android-container budtmo/docker-android:emulator_9.0
          sleep 3600
